### ISSUE TITLE
Feature request: Paid support proposal

### ISSUE THREAD

**Issue by tbrowder** [briandfoy/rakudo-star-chocolatey#15]
I try to have my published Raku modules (40+) be usable on Windows, but I am not an active Windows user, nor do I have a Windows host capable of installing anything newer than MS Pro 10.

In order to help spread the use of Raku to the wide world of Windows, I would like to financially help. I have to go now, but, if interested, please email me at <tom.browder@gmail.com>. I'm @tbrowder on Github and IRC channel \#raku.

**Comment by briandfoy** [comment]
I've activated the Sponsor button for this project, so I'm going to close this issue. But also, I don't think anyone is going to sponsor me at any level that would really catch my attention considering  that they are competing with interesting normal levels of paid work I have. I'm completely willing to manage the sponsorship and pass that on to someone else though.

If there is something in particular that you want, open an issue for that. I think I've covered many of the thing this repo should do in existing issues that I've simply ignored. If you want one of those done, tell me about it. Note that since I maintain a lot of stuff, I know there are lots of things I could do, but I'm also not going to make everything really nice just to make it nice. Part of my time choices are things that people are actually going to use. If someone, anyone, says they need something, that single indication rockets that issue to the top of the list.

But money isn't the thing holding up this project. It's time and interest. I don't know that anyone uses choco or the rakudo-star package on chocolatey. 

It might be more valuable to simply help with the parts you need. I have another project set up for [Github workflows for my Perl modules](https://github.com/briandfoy/github_workflows/tree/master), and maybe we can set up something like that (in another project :) for Raku workflows. 

I'm not a Windows person either. I bought a cheap Surface tablet to have hardware dedicated to Windows when I needed to work on it (VMs were just too slow and bloated). I wouldn't recommend that because Surface's have other weird issues, like not "wake on network access". 

Finally, I haven't kept a close watch on this repo and the chocolatey version of Rakudo Star is a bit behind. I'm happy to add anyone to this project who wants to help out. This particular project isn't that complicated and doesn't need much skill. Run the scripts. I just need to automate it more. I've offered the Raku people comaintainership on the choco repo so it doesn't depend on me, but no one has taken me up on the offer.

**Comment by tbrowder** [comment]
Brian, I'm willing to help, but I'm not going to be able to do anything about it for a while.

Also, I was originally thinking about helping to get the Raku Foundation to sponsor the project, and I would contribute to that. This was to see if anyone here would be intested in applying for such.

BTW, I was one of the sponsors of your Raku (Perl 6) book and have always been amazed at how thorougly your book covered Raku. Ever thought about an updated edition?

**Comment by briandfoy** [comment]
Heh, the foundation would never sponsor me and I wouldn't take their money anyway. There's history there.

I'm not going to do a second edition of the book. I was working with O'Reilly to get it retitled, but I think that's a no go too. I think I might have to start over, and that's a lot of work. And, I don't think the book sold 1,000 copies. Thanks for your support in the first edition though!

Thanks,

**Comment by briandfoy** [comment]
I'm to personally interested in Raku Foundation support, but if someone else is, I don't mind if they participate here.
